apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-virtualservice
  namespace: backend
spec:
  hosts:
    - "user-service"
  gateways:
    - istio-ingress/default-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8080
            host: push-module-service.smartcity.svc.cluster.local
